ATM-Consulting/dolibarr_module_abricot

- includes/class/class.tbl.php
- includes/class/class.tools.php
- includes/js/atm.js
- includes/lib/abricot.lib.php
J'ai fait une petite review du module et quelque petits correctifs.
Globalement, le code est pas super propre et manque très fort de commentaires…
Je vous laisse regarder le FIXME du dernier commit ;)
> Code Review

- includes/class/class.pdo.db.php
Ah bravo !
J'ai perdu 30mn dessus…
> Fixed typo

- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/8)
> NEW ajout default pour des add champs

- includes/class/class.objet_std_dolibarr.php
- includes/class/class.pdo.db.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/9)
> FIX php 7 warning and error

- core/modules/modAbricot.class.php
- inc.core.php
- includes/class/class.list.tbs.php
Pour query, gestion sommes intermédiaire
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/11)
> New group sum

- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/12)
> FIX: Avoid Incorrect datetime value: '0000-00-00 00:00:00' for column 'date_xxxx' at row 1

- includes/class/class.form.core.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/13)
> NEW multiple combo_js + vertical checkbox

- includes/class/class.form.core.php
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/14)
> paramètre pour passer des inputs en ligne

- admin/abricot_setup.php
- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/15)
> NEW option_allow_old_empty_date_value

- includes/class/class.list.tbs.php
- includes/class/html.list.tbs.php
More simple, be smarter ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/16)
> NEW allow to selected field to show

- includes/class/class.pdo.db.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/18)
> SHOW COLUMNS n'existe pas en SQLSRV

- core/modules/modAbricot.class.php
- includes/class/class.list.tbs.php
- langs/en_US/abricot.lang
- langs/fr_FR/abricot.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/19)
> NEW search on NULL

- includes/class/class.list.tbs.php
- includes/class/html.list.tbs.php
hésite pas à me faire des retours pcq je ne perçoit pas la porté global des modifications
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/21)
> New un filtre peut faire de la recherche dans plusieurs champs

- includes/class/class.list.tbs.php
- includes/class/html.list.tbs.php
- includes/js/list.tbs.js
fix #23
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/24)
> optimize download process

- downlist.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/25)
> NEW add BOM char in order to show to excel that it's utf-8 bitch

- core/modules/modAbricot.class.php
- inc.core.php
- includes/class/class.list.tbs.php
NEW export as RAW type to have all data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/26)
> FIX type for view_type arg

- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/27)
> Fix alexis stupidity

- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/30)
> New engine innodb

- includes/class/class.objet_std.php
- script/change-datetime-defaul-to-null.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/31)
> NEW default date value to null

- script/change-datetime-defaul-to-null.php
Le alter table doit être fait avant le update sinon la table est modifié mais pas la valeur
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/33)
> Fix alter table à faire avant le update

- includes/class/class.objet_std.php
Reste à override chaque methode "save()" de chaque class si on souhaite reset des valeurs en testant le "$this->to_clone"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/35)
> New clone method

- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/36)
> NEW LoadAllBy + Manage type of value in sql

- admin/abricot_setup.php
- langs/en_US/abricot.lang
- langs/fr_FR/abricot.lang
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/38)
> added a button in the setup to migrate old datetime to new version

- core/modules/modAbricot.class.php
- inc.core.php
- includes/class/class.listview.php
- includes/class/class.seedobject.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/39)
> New intégration listview et seedobject

- includes/class/class.listview.php
- includes/class/class.seedobject.php
Fix get_class(self) instead get_class($this)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/40)
> Fix createCommon missing

- inc.core.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/41)
> fix : if server force https and not conf.php, js gets blocked

- includes/class/class.iCalReader.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/42)
> use curl if file_get_contents failed

- includes/class/class.objet_std.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/44)
> FIX : on n'affiche l'erreur qu'en mode debug (à améliorer)

- includes/class/class.list.tbs.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/46)
> Fix align uniquement sur titre et pas sur le contenu

- includes/class/class.listview.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/48)
> Fix listview fatal + no data

- includes/class/class.list.tbs.php
- includes/class/html.list.tbs.php
- includes/js/list.tbs.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/47)
> Fix view dolibarr style

- includes/class/class.listview.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/49)
> Fix affiche que la data brut (pas d'eval) + visu

- script/change-text-varchar-encoding-to-conf-value.php
- script/change-text-varchar-encoding-to-utf8.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/50)
> NEW: script to set all db tables default charset to UTF-8

- includes/class/class.template.tbs.php
PR utile pour odtdocs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/51)
> Fix private

- includes/class/class.seedobject.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/52)
> fix warining dolibarr 8.0

- includes/class/class.seedobject.php
J'ai pull le module OF en local avec un Dolibarr 5.0 et je tombe sur quelques fatals
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/53)
> Fix call undefined method avec dolibarr 5.0

- includes/class/class.seedobject.php
la visibilité des méthodes de la class commonObject à changé avec la 7.0 de dolibarr.... on à gagné de très belles erreurs fatales...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/54)
> Fix passage en 7.0

- includes/class/class.listview.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/58)
> Fix affichage avec un renderArray

- includes/lib/admin.lib.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/65)
> New help option for  setup_print_on_off lib

- includes/class/class.list.tbs.php
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/atm-consulting/dolibarr_module_abricot/70)
> FIX: TListviewTBS: hide filters of unselected fields

- includes/class/class.seedobject.php
- tpl/extrafields_setup.tpl.php
ajout de la gestion auto des extrafields dans seed object 
+ ajout tpl pour les modules tpl/extrafields_setup.tpl.php
> New extrafield seedobject

- includes/class/class.listview.php
Ajoute la possibilité d'afficher le formulaire de recherche que l'on veut
> New list view override

- includes/class/class.seedobject.php
Function "setValues" does not take into account type "datetime"
> FIX datetime in function setValues class.seedibject.php

- includes/class/class.objet_std.php
- includes/class/class.seedobject.php
Et aussi : FIX: TObjetStd: remove some PHPStorm warnings and enable some autocompleting, by adding field declaration (when possible) and PHPDoc
> NEW: MAKE var_dump() GREAT AGAIN! Ⓒ

- includes/class/class.list.tbs.php
Accessoirement, ça règle le problème de tri sur la liste d'équipements
> fix sql order by

- includes/class/class.list.tbs.php
https://github.com/ATM-Consulting/dolibarr_module_abricot/pull/83 la regex ne fonctionnait pas.
> Fix order by error

- script/data-migration-ticketSup.php
Script qui permet de migrer les données du module "Ticket Sup" vers le module "Ticket" standard
> New script : ticketsup data migration

- ChangeLog.md
- composer.json
- core/modules/modAbricot.class.php
Changelog format: http://keepachangelog.com/en/1.0.0/
> Changelog added

- script/data-migration-ticketSup.php
escape missing on description and subject fields for ticketsup script
> db escape missing in sql request on ticketsup converting script

- includes/class/class.listview.php
For ListView :
- Fix the operator "IN" in addSqlFromOther that never implode arrays 
- Fix lost filters in navigation.
> Fix_operator_IN_with_array_in_listview

- script/moduleLangTranslator.php
> New script translator

- includes/lib/admin.lib.php
Permet d'ajouter des options ON/OFF qui rechargent automatiquement la page : utile pour les conf imbriquées.
> new setup print on off reload behavior

- includes/class/class.listview.php
add  no-auto-sql-search conf tu be used for each fields
exemple of list view conf part 
``,'search' => array(
'overshootstatus' => array(
'search_type' => 'override', 
'no-auto-sql-search'=>1, 
'override' => $formOvershootStatus
)
)``
> Add override disable auto search query addition

- includes/lib/admin.lib.php
permet d'utiliser des input custom dans les setup de modules
> New custom type for param

- includes/class/class.objet_std.php
- includes/class/class.pdo.db.php
La dernière version de MySQL est plus stricte
> Fix for special col name like status, rank etc

- includes/class/class.form.core.php
Ces paramètres permettent de cadrer les heures disponibles dans le timepicker généré
> Ajout des paramètres "MaxTime" et "MinTime" à la fonction Timepicker

- core/modules/modAbricot.class.php
- includes/lib/admin.lib.php
Une brique nécessaire à la suite des événements et la qualité de nos modules.
Vos retours pour le nommage des functions est encouragé.
> New lib for version compare

- includes/class/class.seedobject.php
Encore une autre PR bien sympa :smiley:
> NEW : SeedObject fetchBy function refactoring

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.listview.php
Allow usage of tooltip key in listview params to add tooltips for cols
> NEW : ListView tooltip param

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.listview.php
# FIX
- FIX  : Listview context detection for columns [2021-01-04]
> FIX : listview contextpage detection

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.listview.php
FIX : correction de la recherche sur les checkbox
> FIX : Setup print input form part

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/substitutionReplace.php
Compatibility V14 - This script aim at replace __REFCLIENT__ with __REF_CLIENT__
> NEW : script substitution replace

- .gitignore
- includes/class/class.pdo.db.php
Pas de charset, utiliser db_type dans le DSN (connexionString), ...
> Pour que ça fonctionne avec PgSQL

- script/moduleLangTranslator.php
- script/moveProvFile.php
- script/password-encrypt-on-all-entities.php
- script/substitutionReplace.php
- script/urlMover.php
pas de changement de version car rentre avec le dernier fix ... c'est la même...
> 3.3 fix dolistore

- script/migrate_ndf.php
Script to migrate the "Note de frais +" module (ATM) to the standard "Expense report" module
> NEW : Script Migration NSFP

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/migrate_ndf.php
> PULLUP Fix ndfp script for compatibility

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/change-datetime-default-to-null.php
- script/change-text-varchar-encoding-to-conf-value.php
- script/common_script.lib.php
apparemment les scripts fonctionnaient pas correctement 
au passage j'ai ajouté une petite gestion de logs et affichage qui fonctionne en bash et web.
> 3.4 fix database integrity script

- script/migrate_ndf.php
> PULLUP 3.4 fix log text

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/data-migration-ticketSup.php
- script/migration_ticketmsg_to_actioncomm.php
Script permettant de rappatrier les données de la table llx_ticket_msg vers llx_actioncomm
/!\ Script différent du script de migration des données de la table llx_ticketsup /!\
> FIX : Script de migration llx_ticket_msg vers llx_actioncomm

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/data-migration-ticketSup.php
- script/migration_ticketmsg_to_actioncomm.php
PR d'origine : https://github.com/ATM-Consulting/dolibarr_module_abricot/pull/150
> PULLUP_Main : Fix script ticketmsg to actioncomm

- includes/lib/admin.lib.php
Displaying to convention doli
Setup page
> New update conv dol

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.listview.php
FIX : Fix divers warnings PHP8
> Fix 3.5 php8 warnings

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.listview.php
FIX : Fix divers warnings PHP8
> PULL UP : Fix 3.5 php8 warnings

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/substitutionReplace.php
- FIX : Substitution script include ticket ref *3.5.2* - **27/02/2023**
> Fix mising substitution

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/lib/admin.lib.php
Fix to show the title and not "Parameter" everywhere
> Fix setup_print_title function

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/lib/admin.lib.php
Prise en compte du paramètre titre dans la fonction setup_print_title
> Fix paramètres Titre

- includes/class/class.objet_std.php
- includes/class/class.seedobject.php
> Fix PostgreSQL compatibilty

- ChangeLog.md
- core/modules/modAbricot.class.php
- script/set-atm-default-config.php
Je propose un script dans lequel on automatiserait les étapes du stepper qui consistent à activer / désactiver une const.
> New script de pré-configuration

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.seedobject.php
Attention perte retrocompat < V6
> NEW : Compatibilité Dolibarr 19

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.seedobject.php
Warning visible pendant la compat de productbycompany
> FIX warning php8.2

- ChangeLog.md
- core/modules/modAbricot.class.php
- includes/class/class.reponse.mail.php
properties of TReponseMail class were not initialized with old PHP constructor
> fix constructor TResponseMail class
